[package]
name = "rust-pixels-processor"
version = "0.1.0"
authors = ["Wiktor Tuminski <wiktor.tuminski@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
bench = false

[features]
default = ["console_error_panic_hook"]

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = 3
lto = 'fat'
panic = 'abort'
strip = "debuginfo"

[build]
rustflags = ["-C", "target-cpu=native"]

[dependencies]
wasm-bindgen = "0.2.93"
js-sys = "0.3.70"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.43"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "pixels_processors_benchmark"
harness = false
