[package]
name = "rust-pixels-processor"
version = "0.1.0"
authors = ["Wiktor Tuminski <wiktor.tuminski@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
js-sys = "0.3.70"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
rstest = "0.23.0"


[profile.release]
opt-level = 3
lto = true
