[package]
name = "rust-pixels-processor"
version = "0.1.0"
authors = ["Wiktor Tuminski <wiktor.tuminski@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
bench = false

[features]
default = ["console_error_panic_hook"]

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = 3
lto = 'fat'
panic = 'abort'
strip = "debuginfo"

[dependencies]
wasm-bindgen = "0.2.95"
js-sys = "0.3.72"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.45"
criterion = { version = "0.5.1", default-features = false, features = [
    "html_reports",
    "plotters",
    "cargo_bench_support",
] }

[[bench]]
name = "pixels_processors_benchmark"
harness = false
